server:
  port: 8089

spring:
  profiles: # ??? ???? ??, ??? ? ???? ??.
    active: dev
  config:
    import: "optional:configserver:http://localhost:8088"
  application:
    name: config
#  cloud:
#    config:
#      uri: http://localhost:8088
management:
  endpoints:
    web:
      exposure:
        include: refresh
